import Head from 'next/head'
import React from 'react'

function Layout(props) {
  return (
    <>
      <Head>
        <title>Fitnessworks {props.title || ''}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full max-w-[1366px] mx-auto">
        { props.children }
      </main>
    </>
  )
}

export default Layout